Repository LethalStation/NovaSector, pull requests merged in 2024-06, with the labels that each got.

#60 Fixes some shuttlestation stuff
  _maps/map_files/lethal/dockyard.dmm
  _maps/shuttles/lethal/outbound_expedition.dmm
  modular_np_lethal/ships_r_us/code/shuttle_parts.dm
Labels: Map Modification

#59 THE MONEY STORE: Credit Rework
  _maps/map_files/lethal/comvat.dmm
  code/game/objects/items/cards_ids.dm
  code/modules/economy/holopay.dm
  modular_np_lethal/deepmaint_stuff/code/order_console_slop/order_console.dm
  modular_np_lethal/epic_loot/code/loot_structures/register.dm
  modular_np_lethal/epic_loot/code/loot_structures/wall_jackets.dm
  modular_np_lethal/money_rework/code/atm.dm
  modular_np_lethal/money_rework/code/atmflatpacked.dm
  modular_np_lethal/money_rework/code/money.dm
  modular_np_lethal/money_rework/code/moneyspawners.dm
  modular_np_lethal/money_rework/icons/atm.dmi
  modular_np_lethal/money_rework/icons/lethalmoney.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/AutoBank.tsx
Labels: Sprites, Map Modification

#66 Adds new Sector 9 themed basic mobs; also adds boss mobs
  _maps/map_files/lethal/comvat.dmm
  modular_np_lethal/mobs/lethalmobs.dm
  modular_np_lethal/mobs/mob_dsword.dm
  modular_np_lethal/mobs/moboutfits.dm
Labels: Map Modification

#68 . = ..() moment
  modular_np_lethal/armor_but_cool/icons/armor_worn.dmi
  modular_np_lethal/mobs/lethalmobs.dm
Labels: Sprites

#74 the armor
  modular_np_lethal/armor_but_cool/code/armor_types/filtre_armor.dm
  modular_np_lethal/armor_but_cool/icons/armor.dmi
  modular_np_lethal/armor_but_cool/icons/armor_worn.dmi
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_heads.dm
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_suit.dm
Labels: Sprites

#85 filtre gaming
  modular_np_lethal/armor_but_cool/code/armor_types/filtre_armor.dm
  modular_np_lethal/armor_but_cool/icons/armor.dmi
  modular_np_lethal/armor_but_cool/icons/armor_worn.dmi
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_heads.dm
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_suit.dm
Labels: Sprites

#91 creates the single most self indulgent PR in ss13 history
  modular_np_lethal/lethalcosmetics/code/kitty_hoodie.dm
  modular_np_lethal/lethalcosmetics/icons/kitty_hoodie.dmi
  modular_np_lethal/lethalcosmetics/icons/kitty_hoodie_obj.dmi
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_suit.dm
  tgstation.dme
Labels: Sprites

#99 pinata helmet... 2
  modular_np_lethal/armor_but_cool/code/armor_types/pinata_armor.dm
  modular_np_lethal/armor_but_cool/icons/armor.dmi
  modular_np_lethal/armor_but_cool/icons/armor_worn.dmi
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_heads.dm
Labels: Sprites

#83 Ports TGMC bullet hit and blood splatter effects (gods least semi-modular PR)
  code/__DEFINES/particles.dm
  code/datums/elements/debris.dm
  code/game/atom/_atom.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/tables_racks.dm
  code/game/shuttle_engines.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/walls.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/bows/_bow.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  icons/effects/particles/generic_particles.dmi
  icons/obj/weapons/guns/muzzle_flash.dmi
  icons/obj/weapons/guns/projectiles.dmi
  modular_nova/modules/barricades/code/barricade.dm
  modular_nova/modules/modular_weapons/code/company_and_or_faction_based/saibasan/laser_guns.dm
  modular_nova/modules/modular_weapons/code/company_and_or_faction_based/saibasan/mode_datums.dm
  modular_nova/modules/polarized_windows/windows.dm
  modular_np_lethal/gun_particles/code/particles.dm
  modular_np_lethal/gun_particles/code/procs.dm
  modular_np_lethal/gun_particles/icons/firesmoke.dmi
  modular_np_lethal/gun_particles/icons/muzzle_flash.dmi
  modular_np_lethal/lethalguns/code/long_rifles.dm
  modular_np_lethal/lethalguns/code/pistol.dm
  tgstation.dme
Labels: Sprites

#100 new custom jacket
  modular_np_lethal/lethalcosmetics/code/loadout_stuff.dm
  modular_np_lethal/lethalcosmetics/icons/freaky_gacket_icon.dmi
  modular_np_lethal/lethalcosmetics/icons/freaky_gacket_onmob.dmi
  modular_np_lethal/loadout_items/actual_loadout_changes/loadout_datum_suit.dm
  tgstation.dme
Labels: Sprites

#101 LethalMobs Expanded - Adds Homies to the Hub
  _maps/map_files/lethal/comvat.dmm
  code/datums/components/trader/trader.dm
  modular_np_lethal/deepmaint_stuff/code/pentola_job_items.dm
  modular_np_lethal/mobs/moboutfits.dm
  modular_np_lethal/mobs/traders/trader_data.dm
  modular_np_lethal/mobs/traders/trader_icons.dmi
  modular_np_lethal/mobs/traders/trader_items.dm
  modular_np_lethal/mobs/traders/traders.dm
  modular_np_lethal/money_rework/code/money.dm
  modular_np_lethal/money_rework/code/moneyspawners.dm
  tgstation.dme
Labels: Sprites, Map Modification

#107 gureibu fix + armor trade description fix + adding water tanks to places for extinguisher refilling
  _maps/map_files/lethal/comvat.dmm
  modular_nova/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/ammo/grenade.dm
  modular_np_lethal/deepmaint_stuff/code/order_console_slop/order_console.dm
  modular_np_lethal/deepmaint_stuff/code/trade_station_types/armor.dm
  modular_np_lethal/epic_loot/code/_basetype.dm
  modular_np_lethal/lethalguns/code/suppressed.dm
Labels: Map Modification
